// use('Supermercado');
// db.getCollection('Productos').insertMany([
//     {'Nombre': 'Leche','Descripción': 'Leche fresca y nutritiva.','Categoria': 'Lácteos','Precio': 2.99,'Codificacion del Producto': {'Lote': '12345','Vencimiento': '2023-12-31'}},
//     {'Nombre': 'Manzanas','Descripción': 'Manzanas frescas y crujientes.','Categoria': 'Frutas','Precio': 1.49,'Codificacion del Producto': {    'Lote': '54321',    'Vencimiento': '2023-10-15'}},
//     {'Nombre': 'Pan','Descripción': 'Pan recién horneado.','Categoria': 'Panadería','Precio': 2.49,'Codificacion del Producto': {    'Lote': '78901',    'Vencimiento': '2023-11-20'}},
//     {'Nombre': 'Carne','Descripción': 'Carne fresca de res.','Categoria': 'Carnes','Precio': 8.99,'Codificacion del Producto': {    'Lote': '24680',    'Vencimiento': '2023-10-25'}},
//     {'Nombre': 'Papas','Descripción': 'Papas frescas y sabrosas.','Categoria': 'Verduras','Precio': 1.99,'Codificacion del Producto': {    'Lote': '13579',    'Vencimiento': '2023-11-10'}},
//     {'Nombre': 'Leche','Descripción': 'Leche fresca y nutritiva.','Categoria': 'Lácteos','Precio': 2.99,'Codificacion del Producto': {  'Lote': '12345',  'Vencimiento': '2023-12-31'}},
//     {'Nombre': 'Manzanas','Descripción': 'Manzanas frescas de temporada.','Categoria': 'Frutas','Precio': 1.49,'Codificacion del Producto': {  'Lote': '67890',  'Vencimiento': '2023-10-15'}},
//     {'Nombre': 'Pan','Descripción': 'Pan de trigo blanco.','Categoria': 'Panadería','Precio': 2.49,'Codificacion del Producto': {  'Lote': '54321',  'Vencimiento': '2023-10-12'}},
//     {'Nombre': 'Carne','Descripción': 'Carne de res de alta calidad.','Categoria': 'Carnes','Precio': 8.99,'Codificacion del Producto': {  'Lote': 'A123',  'Vencimiento': '2023-10-20'}},
//     {'Nombre': 'Papas','Descripción': 'Papas frescas de la granja.','Categoria': 'Verduras','Precio': 1.99,'Codificacion del Producto': {  'Lote': 'B456',  'Vencimiento': '2023-10-18'}},
//     {'Nombre': 'Cebollas','Descripción': 'Cebollas amarillas orgánicas.','Categoria': 'Verduras','Precio': 0.99,'Codificacion del Producto': {  'Lote': 'C789',  'Vencimiento': '2023-10-22'}},
//     {'Nombre': 'Cereal','Descripción': 'Cereal integral con fibra.','Categoria': 'Desayuno','Precio': 3.49,'Codificacion del Producto': {  'Lote': 'D123',  'Vencimiento': '2024-01-15'}},
//     {'Nombre': 'Yogur','Descripción': 'Yogur natural sin azúcar.','Categoria': 'Lácteos','Precio': 2.29,'Codificacion del Producto': {  'Lote': 'E456',  'Vencimiento': '2023-10-15'}},
//     {'Nombre': 'Huevos','Descripción': 'Docena de huevos frescos.','Categoria': 'Huevos','Precio': 2.99,'Codificacion del Producto': {  'Lote': 'F789',  'Vencimiento': '2023-10-25'}},
//     {'Nombre': 'Tocino','Descripción': 'Tocino ahumado de cerdo.','Categoria': 'Carnes','Precio': 5.99,'Codificacion del Producto': {  'Lote': 'G123',  'Vencimiento': '2023-10-19'},'Oferta': '¡Compra 2, lleva 1 gratis!','Origen': 'Local'},
//     {'Nombre': 'Soda','Descripción': 'Refresco de cola en lata.','Categoria': 'Bebidas','Precio': 1.29,'Codificacion del Producto': {  'Lote': 'H456',  'Vencimiento': '2024-02-28'},'Sabor': 'Cola','Tamaño': '355 ml'},
//     {'Nombre': 'Chips','Descripción': 'Papas fritas saladas.','Categoria': 'Aperitivos','Precio': 2.49,'Codificacion del Producto': {  'Lote': 'I789',  'Vencimiento': '2023-10-12'},'Sabor': 'Sal y vinagre','Marca': 'Crunchy Munch'},
//     {'Nombre': 'Galletas','Descripción': 'Galletas de chocolate con chispas.','Categoria': 'Repostería','Precio': 3.99,'Codificacion del Producto': {  'Lote': 'J123',  'Vencimiento': '2024-03-10'},'Tipo': 'Chocolate','Peso': '250g'},
//     {'Nombre': 'Pan integral','Descripción': 'Pan integral de granos enteros.','Categoria': 'Panadería','Precio': 2.79,'Codificacion del Producto': {  'Lote': 'K123',  'Vencimiento': '2023-10-12'},'Marca': 'WholeGrain Bakers','Sin gluten': false},
//     {'Nombre': 'Peras','Descripción': 'Peras maduras y jugosas.','Categoria': 'Frutas','Precio': 1.79,'Codificacion del Producto': {  'Lote': 'L123',  'Vencimiento': '2023-10-20'}},
//     {'Nombre': 'Uvas','Descripción': 'Uvas sin semillas.','Categoria': 'Frutas','Precio': 2.29,'Codificacion del Producto': {  'Lote': 'M123',  'Vencimiento': '2023-10-15'}},
//     {'Nombre': 'Pollo','Descripción': 'Pollo fresco de corral.','Categoria': 'Carnes','Precio': 6.49,'Codificacion del Producto': {  'Lote': 'N123',  'Vencimiento': '2023-10-22'}},
//     {'Nombre': 'Verduras','Descripción': 'Mezcla de verduras congeladas.','Categoria': 'Congelados','Precio': 2.99,'Codificacion del Producto': {  'Lote': 'O123',  'Vencimiento': '2024-01-10'}},
//     {'Nombre': 'Arroz','Descripción': 'Arroz blanco de grano largo.','Categoria': 'Granos','Precio': 1.99,'Codificacion del Producto': {  'Lote': 'P123',  'Vencimiento': '2024-03-01'}},
//     {'Nombre': 'Aceite de Oliva','Descripción': 'Aceite de oliva virgen extra.','Categoria': 'Aceites','Precio': 4.99,'Codificacion del Producto': {  'Lote': 'Q123',  'Vencimiento': '2024-04-15'}},
//     {'Nombre': 'Naranjas','Descripción': 'Naranjas frescas de Valencia.','Categoria': 'Frutas','Precio': 1.29,'Codificacion del Producto': {  'Lote': 'R123',  'Vencimiento': '2023-11-30'}},
//     {'Nombre': 'Miel','Descripción': 'Miel orgánica de abeja.','Categoria': 'Endulzantes','Precio': 3.49,'Codificacion del Producto': {  'Lote': 'S123',  'Vencimiento': '2024-05-20'}},
//     {'Nombre': 'Cerveza','Descripción': 'Cerveza artesanal IPA.','Categoria': 'Bebidas alcohólicas','Precio': 5.99,'Codificacion del Producto': {  'Lote': 'T123',  'Vencimiento': '2023-12-31'}},
//     {'Nombre': 'Pasta','Descripción': 'Pasta de trigo integral.','Categoria': 'Pasta','Precio': 1.79,'Codificacion del Producto': {'Lote': 'U123','Vencimiento': '2024-06-10'}},
//     {'Nombre': 'Leche', 'Descripcion': 'Leche entera, 1 litro.', 'Categoria': 'Lacteos', 'Precio': 2.99, 'CodificacionProducto': { 'Lote': 'L123', 'Vencimiento': '2023-12-15' } },
//     { 'Nombre': 'Manzanas', 'Descripcion': 'Manzanas frescas, 1 kg.', 'Categoria': 'Frutas', 'Precio': 4.49, 'CodificacionProducto': { 'Lote': 'M456', 'Vencimiento': '2023-10-20' } },
//     { 'Nombre': 'Pan', 'Descripcion': 'Pan de trigo, 500g.', 'Categoria': 'Panaderia', 'Precio': 1.99, 'CodificacionProducto': { 'Lote': 'P789', 'Vencimiento': '2023-10-18' } },
//     { 'Nombre': 'Carne', 'Descripcion': 'Carne de res, 1 kg.', 'Categoria': 'Carnes', 'Precio': 9.99, 'CodificacionProducto': { 'Lote': 'C123', 'Vencimiento': '2023-10-25' } },
//     { 'Nombre': 'Papas', 'Descripcion': 'Papas frescas, 2 kg.', 'Categoria': 'Verduras', 'Precio': 3.99, 'CodificacionProducto': { 'Lote': 'P456', 'Vencimiento': '2023-10-22' } },
//     { 'Nombre': 'Cebollas', 'Descripcion': 'Cebollas, 500g.', 'Categoria': 'Verduras', 'Precio': 1.49, 'CodificacionProducto': { 'Lote': 'C789', 'Vencimiento': '2023-10-20' } },
//     { 'Nombre': 'Cereal', 'Descripcion': 'Cereal integral, 500g.', 'Categoria': 'Cereales', 'Precio': 3.99, 'CodificacionProducto': { 'Lote': 'CR123', 'Vencimiento': '2024-01-15' } },
//     { 'Nombre': 'Yogur', 'Descripcion': 'Yogur natural, 500g.', 'Categoria': 'Lacteos', 'Precio': 2.29, 'CodificacionProducto': { 'Lote': 'Y123', 'Vencimiento': '2023-10-17' } },
//     { 'Nombre': 'Huevos', 'Descripcion': 'Huevos frescos, docena.', 'Categoria': 'Huevos', 'Precio': 2.99, 'CodificacionProducto': { 'Lote': 'H123', 'Vencimiento': '2023-10-19' } },
//     { 'Nombre': 'Tocino', 'Descripcion': 'Tocino ahumado, 250g.', 'Categoria': 'Carnes', 'Precio': 4.99, 'CodificacionProducto': { 'Lote': 'T456', 'Vencimiento': '2023-10-23' } },
//     { 'Nombre': 'Soda', 'Descripcion': 'Soda, 2 litros.', 'Categoria': 'Bebidas', 'Precio': 1.00, 'CodificacionProducto': { 'Lote': 'S123', 'Vencimiento': '2023-11-30' } },
//     { 'Nombre': 'Chips', 'Descripcion': 'Chips de maíz, 200g.', 'Categoria': 'Aperitivos', 'Precio': 2.49, 'CodificacionProducto': { 'Lote': 'CH123', 'Vencimiento': '2024-02-28' } },
//     { 'Nombre': 'Galletas', 'Descripcion': 'Galletas de chocolate, 300g.', 'Categoria': 'Aperitivos', 'Precio': 1.99, 'CodificacionProducto': { 'Lote': 'GA123', 'Vencimiento': '2023-12-31' } },
//     { 'Nombre': 'Pan integral', 'Descripcion': 'Pan integral, 500g.', 'Categoria': 'Panaderia', 'Precio': 2.49, 'CodificacionProducto': { 'Lote': 'PI123', 'Vencimiento': '2023-10-18' } },
//     { 'Nombre': 'Peras', 'Descripcion': 'Peras frescas, 1 kg.', 'Categoria': 'Frutas', 'Precio': 3.99, 'CodificacionProducto': { 'Lote': 'PE123', 'Vencimiento': '2023-10-21' } },
//     { 'Nombre': 'Uvas', 'Descripcion': 'Uvas frescas, 500g.', 'Categoria': 'Frutas', 'Precio': 2.99, 'CodificacionProducto': { 'Lote': 'U123', 'Vencimiento': '2023-10-20' } },
//     { 'Nombre': 'Pollo', 'Descripcion': 'Pollo entero, 1 kg.', 'Categoria': 'Carnes', 'Precio': 6.99, 'CodificacionProducto': { 'Lote': 'PO123', 'Vencimiento': '2023-10-24' } },
//     { 'Nombre': 'Verduras', 'Descripcion': 'Verduras surtidas, 500g.', 'Categoria': 'Verduras', 'Precio': 2.29, 'CodificacionProducto': { 'Lote': 'V123', 'Vencimiento': '2023-10-19' } },
//     { 'Nombre': 'Arroz', 'Descripcion': 'Arroz blanco, 1 kg.', 'Categoria': 'Cereales', 'Precio': 1.99, 'CodificacionProducto': { 'Lote': 'AR123', 'Vencimiento': '2023-11-15' } },
//     { 'Nombre': 'Aceite de Coco', 'Descripcion': 'Aceite de coco virgen extra.', 'Categoria': 'Aceites', 'Precio': 6.99, 'CodificacionProducto': { 'Lote': 'U234', 'Vencimiento': '2024-05-10' } },
//     { 'Nombre': 'Mantequilla', 'Descripcion': 'Mantequilla sin sal, 250g.', 'Categoria': 'Lacteos', 'Precio': 3.49, 'CodificacionProducto': { 'Lote': 'M234', 'Vencimiento': '2023-11-25' } },
//     { 'Nombre': 'Salmón', 'Descripcion': 'Filete de salmón fresco, 200g.', 'Categoria': 'Pescados', 'Precio': 7.99, 'CodificacionProducto': { 'Lote': 'S456', 'Vencimiento': '2023-10-26' } },
//     { 'Nombre': 'Pasta', 'Descripcion': 'Pasta italiana, 500g.', 'Categoria': 'Pasta', 'Precio': 1.79, 'CodificacionProducto': { 'Lote': 'PA123', 'Vencimiento': '2023-12-31' } },
//     { 'Nombre': 'Avena', 'Descripcion': 'Avena en hojuelas, 500g.', 'Categoria': 'Cereales', 'Precio': 2.19, 'CodificacionProducto': { 'Lote': 'AV123', 'Vencimiento': '2024-01-20' } },
//     { 'Nombre': 'Miel', 'Descripcion': 'Miel natural, 500g.', 'Categoria': 'Endulzantes', 'Precio': 5.99, 'CodificacionProducto': { 'Lote': 'MI123', 'Vencimiento': '2023-12-31' } },
//     { 'Nombre': 'Queso', 'Descripcion': 'Queso cheddar, 250g.', 'Categoria': 'Lacteos', 'Precio': 4.29, 'CodificacionProducto': { 'Lote': 'Q123', 'Vencimiento': '2023-10-28' } },
//     { 'Nombre': 'Pimienta', 'Descripcion': 'Pimienta molida, 50g.', 'Categoria': 'Especias', 'Precio': 1.49, 'CodificacionProducto': { 'Lote': 'PIM123', 'Vencimiento': '2023-12-31' } },
//     { 'Nombre': 'Chocolate', 'Descripcion': 'Chocolate negro, 100g.', 'Categoria': 'Reposteria', 'Precio': 2.99, 'CodificacionProducto': { 'Lote': 'CHOC123', 'Vencimiento': '2023-11-15' } },
//     { 'Nombre': 'Café', 'Descripcion': 'Café molido, 250g.', 'Categoria': 'Bebidas', 'Precio': 4.49, 'CodificacionProducto': { 'Lote': 'CAFE123', 'Vencimiento': '2023-11-30' } },
//     { 'Nombre': 'Mantequilla de Maní', 'Descripcion': 'Mantequilla de maní natural, 500g.', 'Categoria': 'Frutos Secos', 'Precio': 3.99, 'CodificacionProducto': { 'Lote': 'MM123', 'Vencimiento': '2024-02-10' } },
//     { 'Nombre': 'Vinagre', 'Descripcion': 'Vinagre de vino tinto, 500ml.', 'Categoria': 'Condimentos', 'Precio': 1.79, 'CodificacionProducto': { 'Lote': 'VINA123', 'Vencimiento': '2023-12-31' } },
//     { 'Nombre': 'Mostaza', 'Descripcion': 'Mostaza amarilla, 200g.', 'Categoria': 'Condimentos', 'Precio': 0.99, 'CodificacionProducto': { 'Lote': 'MOS123', 'Vencimiento': '2023-12-31' } },
//     { 'Nombre': 'Panecillos', 'Descripcion': 'Panecillos de avena, paquete de 6.', 'Categoria': 'Panaderia', 'Precio': 2.79, 'CodificacionProducto': { 'Lote': 'PANE123', 'Vencimiento': '2023-10-17' } },
//     { 'Nombre': 'Helado', 'Descripcion': 'Helado de vainilla, 1 litro.', 'Categoria': 'Helados', 'Precio': 3.99, 'CodificacionProducto': { 'Lote': 'HEL123', 'Vencimiento': '2023-11-15' } },
//     { 'Nombre': 'Pepinillos', 'Descripcion': 'Pepinillos encurtidos, 500g.', 'Categoria': 'Encurtidos', 'Precio': 1.69, 'CodificacionProducto': { 'Lote': 'PEPI123', 'Vencimiento': '2023-12-31' } },
//     { 'Nombre': 'Salsa de Tomate', 'Descripcion': 'Salsa de tomate, 500g.', 'Categoria': 'Salsas', 'Precio': 1.29, 'CodificacionProducto': { 'Lote': 'ST123', 'Vencimiento': '2023-11-30' } },
//     { 'Nombre': 'Nueces', 'Descripcion': 'Nueces naturales, 250g.', 'Categoria': 'Frutos Secos', 'Precio': 5.49, 'CodificacionProducto': { 'Lote': 'NU123', 'Vencimiento': '2024-02-28' } },
//     { 'Nombre': 'Jugo de Naranja', 'Descripcion': 'Jugo de naranja natural, 1 litro.', 'Categoria': 'Bebidas', 'Precio': 2.49, 'CodificacionProducto': { 'Lote': 'JN123', 'Vencimiento': '2023-11-30' } },
//     { 'Nombre': 'Panceta', 'Descripcion': 'Panceta ahumada, 250g.', 'Categoria': 'Carnes', 'Precio': 4.79, 'CodificacionProducto': { 'Lote': 'PAN123', 'Vencimiento': '2023-10-23' } },
//     { 'Nombre': 'Mermelada', 'Descripcion': 'Mermelada de fresa, 400g.', 'Categoria': 'Reposteria', 'Precio': 2.79, 'CodificacionProducto': { 'Lote': 'MER123', 'Vencimiento': '2023-12-31' } },
//     { 'Nombre': 'Hamburguesas', 'Descripcion': 'Hamburguesas de res, paquete de 4.', 'Categoria': 'Carnes', 'Precio': 6.29, 'CodificacionProducto': { 'Lote': 'HAM123', 'Vencimiento': '2023-10-27' } },
//     { 'Nombre': 'Salchichas', 'Descripcion': 'Salchichas de pavo, paquete de 8.', 'Categoria': 'Embutidos', 'Precio': 3.29, 'CodificacionProducto': { 'Lote': 'SAL123', 'Vencimiento': '2023-10-30' } },
//     { 'Nombre': 'Aceitunas', 'Descripcion': 'Aceitunas verdes rellenas, 250g.', 'Categoria': 'Encurtidos', 'Precio': 1.99, 'CodificacionProducto': { 'Lote': 'ACEI123', 'Vencimiento': '2023-12-31' } },
//     {"Nombre": "Leche", "Descripcion": "Leche entera, 1 litro.", "Categoria": "Lacteos", "Precio": 2.99, "CodificacionProducto": { "Lote": "L234", "Vencimiento": "2023-11-10" } },
//     { "Nombre": "Manzanas", "Descripcion": "Manzanas frescas, 1 kg.", "Categoria": "Frutas", "Precio": 4.49, "CodificacionProducto": { "Lote": "M567", "Vencimiento": "2023-10-18" } },
//     { "Nombre": "Pan", "Descripcion": "Pan de trigo, 500g.", "Categoria": "Panaderia", "Precio": 1.99 },
//     { "Nombre": "Carne", "Descripcion": "Carne de res, 1 kg.", "Categoria": "Carnes", "Precio": 9.99, "CodificacionProducto": { "Lote": "C456", "Vencimiento": "2023-10-25" } },
//     { "Nombre": "Papas", "Descripcion": "Papas frescas, 2 kg.", "Categoria": "Verduras", "Precio": 3.99 },
//     { "Nombre": "Cebollas", "Descripcion": "Cebollas, 500g.", "Categoria": "Verduras", "Precio": 1.49 },
//     { "Nombre": "Cereal", "Descripcion": "Cereal integral, 500g.", "Categoria": "Cereales", "Precio": 3.99, "CodificacionProducto": { "Lote": "CR567", "Vencimiento": "2024-01-15" } },
//     { "Nombre": "Yogur", "Descripcion": "Yogur natural, 500g.", "Categoria": "Lacteos", "Precio": 2.29 },
//     { "Nombre": "Huevos", "Descripcion": "Huevos frescos, docena.", "Categoria": "Huevos", "Precio": 2.99, "CodificacionProducto": { "Lote": "H234", "Vencimiento": "2023-10-19" } },
//     { "Nombre": "Tocino", "Descripcion": "Tocino ahumado, 250g.", "Categoria": "Carnes", "Precio": 4.99 },
//     { "Nombre": "Soda", "Descripcion": "Soda, 2 litros.", "Categoria": "Bebidas", "Precio": 1.00 },
//     { "Nombre": "Chips", "Descripcion": "Chips de maíz, 200g.", "Categoria": "Aperitivos", "Precio": 2.49 },
//     { "Nombre": "Galletas", "Descripcion": "Galletas de chocolate, 300g.", "Categoria": "Aperitivos", "Precio": 1.99 },
//     { "Nombre": "Pan integral", "Descripcion": "Pan integral, 500g.", "Categoria": "Panaderia", "Precio": 2.49, "CodificacionProducto": { "Lote": "PI567", "Vencimiento": "2023-10-18" } },
//     { "Nombre": "Peras", "Descripcion": "Peras frescas, 1 kg.", "Categoria": "Frutas", "Precio": 3.99 },
//     { "Nombre": "Uvas", "Descripcion": "Uvas frescas, 500g.", "Categoria": "Frutas", "Precio": 2.99 },
//     { "Nombre": "Pollo", "Descripcion": "Pollo entero, 1 kg.", "Categoria": "Carnes", "Precio": 6.99, "CodificacionProducto": { "Lote": "PO456", "Vencimiento": "2023-10-24" } },
//     { "Nombre": "Verduras", "Descripcion": "Verduras surtidas, 500g.", "Categoria": "Verduras", "Precio": 2.29 },
//     { "Nombre": "Arroz", "Descripcion": "Arroz blanco, 1 kg.", "Categoria": "Cereales", "Precio": 1.99, "CodificacionProducto": { "Lote": "AR567", "Vencimiento": "2023-11-15" } },
//     { "Nombre": "Aceite de Coco", "Descripcion": "Aceite de coco virgen extra.", "Categoria": "Aceites", "Precio": 6.99, "CodificacionProducto": { "Lote": "U345", "Vencimiento": "2024-05-10" } },
//     { "Nombre": "Mantequilla", "Descripcion": "Mantequilla sin sal, 250g.", "Categoria": "Lacteos", "Precio": 3.49 },
//     { "Nombre": "Salmón", "Descripcion": "Filete de salmón fresco, 200g.", "Categoria": "Pescados", "Precio": 7.99, "CodificacionProducto": { "Lote": "S567", "Vencimiento": "2023-10-26" } },
//     { "Nombre": "Pasta", "Descripcion": "Pasta italiana, 500g.", "Categoria": "Pasta", "Precio": 1.79 },
//     { "Nombre": "Avena", "Descripcion": "Avena en hojuelas, 500g.", "Categoria": "Cereales", "Precio": 2.19 },
//     { "Nombre": "Miel", "Descripcion": "Miel natural, 500g.", "Categoria": "Endulzantes", "Precio": 5.99, "CodificacionProducto": { "Lote": "MI567", "Vencimiento": "2023-12-31" } },
//     { "Nombre": "Queso", "Descripcion": "Queso cheddar, 250g.", "Categoria": "Lacteos", "Precio": 4.29 },
//     { "Nombre": "Pimienta", "Descripcion": "Pimienta molida, 50g.", "Categoria": "Especias", "Precio": 1.49 },
//     { "Nombre": "Chocolate", "Descripcion": "Chocolate negro, 100g.", "Categoria": "Reposteria", "Precio": 2.99, "CodificacionProducto": { "Lote": "CHOC567", "Vencimiento": "2023-11-15" } },
//     { "Nombre": "Café", "Descripcion": "Café molido, 250g.", "Categoria": "Bebidas", "Precio": 4.49 },
//     { "Nombre": "Mantequilla de Maní", "Descripcion": "Mantequilla de maní natural, 500g.", "Categoria": "Frutos Secos", "Precio": 3.99 },
//     { "Nombre": "Vinagre", "Descripcion": "Vinagre de vino tinto, 500ml.", "Categoria": "Condimentos", "Precio": 1.79, "CodificacionProducto": { "Lote": "VINA567", "Vencimiento": "2023-12-31" } },
//     { "Nombre": "Mostaza", "Descripcion": "Mostaza amarilla, 200g.", "Categoria": "Condimentos", "Precio": 0.99 },
//     { "Nombre": "Panecillos", "Descripcion": "Panecillos de avena, paquete de 6.", "Categoria": "Panaderia", "Precio": 2.79 },
//     { "Nombre": "Helado", "Descripcion": "Helado de vainilla, 1 litro.", "Categoria": "Helados", "Precio": 3.99, "CodificacionProducto": { "Lote": "HEL567", "Vencimiento": "2023-11-15" } },
//     { "Nombre": "Pepinillos", "Descripcion": "Pepinillos encurtidos, 500g.", "Categoria": "Encurtidos", "Precio": 1.69 },
//     { "Nombre": "Salsa de Tomate", "Descripcion": "Salsa de tomate, 500g.", "Categoria": "Salsas", "Precio": 1.29 },
//     { "Nombre": "Nueces", "Descripcion": "Nueces naturales, 250g.", "Categoria": "Frutos Secos", "Precio": 5.49 },
//     { "Nombre": "Jugo de Naranja", "Descripcion": "Jugo de naranja natural, 1 litro.", "Categoria": "Bebidas", "Precio": 2.49 },
//     { "Nombre": "Panceta", "Descripcion": "Panceta ahumada, 250g.", "Categoria": "Carnes", "Precio": 4.79, "CodificacionProducto": { "Lote": "PAN567", "Vencimiento": "2023-10-23" } },
//     { "Nombre": "Mermelada", "Descripcion": "Mermelada de fresa, 400g.", "Categoria": "Reposteria", "Precio": 2.79 },
//     { "Nombre": "Hamburguesas", "Descripcion": "Hamburguesas de res, paquete de 4.", "Categoria": "Carnes", "Precio": 6.29 },
//     { "Nombre": "Salchichas", "Descripcion": "Salchichas de pavo, paquete de 8.", "Categoria": "Embutidos", "Precio": 3.29 },
//     { "Nombre": "Aceitunas", "Descripcion": "Aceitunas verdes rellenas, 250g.", "Categoria": "Encurtidos", "Precio": 1.99 },
//     {"Nombre": "Queso", "Descripcion": "Queso cheddar, 250g.", "Categoria": "Lacteos", "Precio": 4.29, "CodificacionProducto": { "Lote": "Q123", "Vencimiento": "2023-10-28" } },
//     { "Nombre": "Pimienta", "Descripcion": "Pimienta molida, 50g.", "Categoria": "Especias", "Precio": 1.49, "CodificacionProducto": { "Lote": "PIM123", "Vencimiento": "2023-12-31" } },
//     { "Nombre": "Chocolate", "Descripcion": "Chocolate negro, 100g.", "Categoria": "Reposteria", "Precio": 2.99, "CodificacionProducto": { "Lote": "CHOC123", "Vencimiento": "2023-11-15" } },
//     { "Nombre": "Café", "Descripcion": "Café molido, 250g.", "Categoria": "Bebidas", "Precio": 4.49, "CodificacionProducto": { "Lote": "CAFE123", "Vencimiento": "2023-11-30" } },
//     { "Nombre": "Mantequilla de Maní", "Descripcion": "Mantequilla de maní natural, 500g.", "Categoria": "Frutos Secos", "Precio": 3.99, "CodificacionProducto": { "Lote": "MM123", "Vencimiento": "2024-02-10" } },
//     { "Nombre": "Vinagre", "Descripcion": "Vinagre de vino tinto, 500ml.", "Categoria": "Condimentos", "Precio": 1.79, "CodificacionProducto": { "Lote": "VINA123", "Vencimiento": "2023-12-31" } },
//     { "Nombre": "Mostaza", "Descripcion": "Mostaza amarilla, 200g.", "Categoria": "Condimentos", "Precio": 0.99, "CodificacionProducto": { "Lote": "MOS123", "Vencimiento": "2023-12-31" } },
//     { "Nombre": "Panecillos", "Descripcion": "Panecillos de avena, paquete de 6.", "Categoria": "Panaderia", "Precio": 2.79, "CodificacionProducto": { "Lote": "PANE123", "Vencimiento": "2023-10-17" } },
//     { "Nombre": "Helado", "Descripcion": "Helado de vainilla, 1 litro.", "Categoria": "Helados", "Precio": 3.99, "CodificacionProducto": { "Lote": "HEL123", "Vencimiento": "2023-11-15" } },
//     { "Nombre": "Pepinillos", "Descripcion": "Pepinillos encurtidos, 500g.", "Categoria": "Encurtidos", "Precio": 1.69, "CodificacionProducto": { "Lote": "PEPI123", "Vencimiento": "2023-12-31" } },
//     { "Nombre": "Salsa de Tomate", "Descripcion": "Salsa de tomate, 500g.", "Categoria": "Salsas", "Precio": 1.29, "CodificacionProducto": { "Lote": "ST123", "Vencimiento": "2023-11-30" } },
//     { "Nombre": "Nueces", "Descripcion": "Nueces naturales, 250g.", "Categoria": "Frutos Secos", "Precio": 5.49, "CodificacionProducto": { "Lote": "NU123", "Vencimiento": "2024-02-28" } },
//     { "Nombre": "Jugo de Naranja", "Descripcion": "Jugo de naranja natural, 1 litro.", "Categoria": "Bebidas", "Precio": 2.49, "CodificacionProducto": { "Lote": "JN123", "Vencimiento": "2023-11-30" } },
//     { "Nombre": "Panceta", "Descripcion": "Panceta ahumada, 250g.", "Categoria": "Carnes", "Precio": 4.79, "CodificacionProducto": { "Lote": "PAN567", "Vencimiento": "2023-10-23" } },
//     { "Nombre": "Mermelada", "Descripcion": "Mermelada de fresa, 400g.", "Categoria": "Reposteria", "Precio": 2.79, "CodificacionProducto": { "Lote": "MER123", "Vencimiento": "2023-12-31" } },
//     { "Nombre": "Hamburguesas", "Descripcion": "Hamburguesas de res, paquete de 4.", "Categoria": "Carnes", "Precio": 6.29, "CodificacionProducto": { "Lote": "HAM123", "Vencimiento": "2023-10-27" } },
//     { "Nombre": "Salchichas", "Descripcion": "Salchichas de pavo, paquete de 8.", "Categoria": "Embutidos", "Precio": 3.29, "CodificacionProducto": { "Lote": "SAL123", "Vencimiento": "2023-10-30" } },
//     { "Nombre": "Aceitunas", "Descripcion": "Aceitunas verdes rellenas, 250g.", "Categoria": "Encurtidos", "Precio": 1.99, "CodificacionProducto": { "Lote": "ACEI123", "Vencimiento": "2023-12-31" } },
//     { "Nombre": "Sirope de Arce", "Descripcion": "Sirope de arce puro, 250ml.", "Categoria": "Endulzantes", "Precio": 7.99 },
//     { "Nombre": "Pasta de Dientes", "Descripcion": "Pasta de dientes fluorada, 150g.", "Categoria": "Higiene", "Precio": 2.49 },
//     { "Nombre": "Shampoo", "Descripcion": "Shampoo revitalizante, 400ml.", "Categoria": "Higiene", "Precio": 5.99 },
//     { "Nombre": "Toallas de Papel", "Descripcion": "Toallas de papel absorbentes, paquete de 6.", "Categoria": "Hogar", "Precio": 3.79 },
//     { "Nombre": "Lavavajillas", "Descripcion": "Detergente para lavavajillas, 500ml.", "Categoria": "Limpieza", "Precio": 2.99 },
//     { "Nombre": "Barras de Granola", "Descripcion": "Barras de granola, paquete de 8.", "Categoria": "Snacks", "Precio": 4.49 },
//     { "Nombre": "Té Verde", "Descripcion": "Té verde orgánico, caja de 20 bolsitas.", "Categoria": "Bebidas", "Precio": 3.29 },
//     { "Nombre": "Salmón", "Descripcion": "Filete de salmón fresco, 200g.", "Categoria": "Pescados", "Precio": 7.99, "CodificacionProducto": { "Lote": "S567", "Vencimiento": "2023-10-26" } },
//     { "Nombre": "Azúcar", "Descripcion": "Azúcar blanca, 1 kg.", "Categoria": "Endulzantes", "Precio": 1.79 },
//     { "Nombre": "Papel Higiénico", "Descripcion": "Papel higiénico suave, paquete de 12.", "Categoria": "Hogar", "Precio": 6.49 },
//     { "Nombre": "Huevos", "Descripcion": "Huevos frescos, docena.", "Categoria": "Huevos", "Precio": 2.99, "CodificacionProducto": { "Lote": "H234", "Vencimiento": "2023-10-19" } },
//     { "Nombre": "Salmón Ahumado", "Descripcion": "Salmón ahumado, 150g.", "Categoria": "Pescados", "Precio": 8.49 },
//     { "Nombre": "Queso Parmesano", "Descripcion": "Queso parmesano rallado, 100g.", "Categoria": "Lacteos", "Precio": 3.79 },
//     { "Nombre": "Mantequilla", "Descripcion": "Mantequilla sin sal, 250g.", "Categoria": "Lacteos", "Precio": 3.49 },
//     { "Nombre": "Aceitunas Rellenas", "Descripcion": "Aceitunas rellenas de pimientos, 200g.", "Categoria": "Encurtidos", "Precio": 2.19 },
//     { "Nombre": "Vino Tinto", "Descripcion": "Vino tinto reserva, 750ml.", "Categoria": "Bebidas", "Precio": 9.99 },
//     { "Nombre": "Crema de Cacahuate", "Descripcion": "Crema de cacahuate natural, 400g.", "Categoria": "Frutos Secos", "Precio": 5.29 },
//     { "Nombre": "Tortillas de Maíz", "Descripcion": "Tortillas de maíz, paquete de 12.", "Categoria": "Panes", "Precio": 1.99 },
//     { "Nombre": "Salsa de Soja", "Descripcion": "Salsa de soja tradicional, 250ml.", "Categoria": "Salsas", "Precio": 2.29 },
//     { "Nombre": "Té de Manzanilla", "Descripcion": "Té de manzanilla, caja de 25 bolsitas.", "Categoria": "Bebidas", "Precio": 2.99 },
//     { "Nombre": "Champiñones", "Descripcion": "Champiñones frescos, 200g.", "Categoria": "Verduras", "Precio": 1.79 },
//     { "Nombre": "Salmón enlatado", "Descripcion": "Salmón enlatado al natural, 150g.", "Categoria": "Pescados", "Precio": 4.99 },
//     { "Nombre": "Crema para la Piel", "Descripcion": "Crema hidratante para la piel, 200ml.", "Categoria": "Higiene", "Precio": 6.49 },
//     { "Nombre": "Gel de Ducha", "Descripcion": "Gel de ducha revitalizante, 500ml.", "Categoria": "Higiene", "Precio": 3.99 },
//     { "Nombre": "Hojuelas de Maíz", "Descripcion": "Hojuelas de maíz azucaradas, 400g.", "Categoria": "Cereales", "Precio": 2.49 },
//     { "Nombre": "Champú para Mascotas", "Descripcion": "Champú suave para mascotas, 250ml.", "Categoria": "Mascotas", "Precio": 3.29 },
//     { "Nombre": "Galletas para Perros", "Descripcion": "Galletas para perros, paquete de 200g.", "Categoria": "Mascotas", "Precio": 1.99 },
//     { "Nombre": "Comida para Gatos", "Descripcion": "Comida para gatos, lata de 400g.", "Categoria": "Mascotas", "Precio": 2.79 },
//     { "Nombre": "Papel Aluminio", "Descripcion": "Rollo de papel aluminio, 30 metros.", "Categoria": "Hogar", "Precio": 1.99 },
//     { "Nombre": "Limpiador Multiusos", "Descripcion": "Limpiador multiusos, 500ml.", "Categoria": "Limpieza", "Precio": 2.79 },
//     { "Nombre": "Detergente para Ropa", "Descripcion": "Detergente líquido para ropa, 1 litro.", "Categoria": "Limpieza", "Precio": 4.99 },
//     { "Nombre": "Pasta Dental para Niños", "Descripcion": "Pasta dental para niños, sabor fresa, 100g.", "Categoria": "Higiene", "Precio": 1.99 },
//     {"Nombre": "Jabón de Manos", "Descripcion": "Jabón líquido para manos, 250ml.", "Categoria": "Higiene", "Precio": 1.99 },
//     { "Nombre": "Pimienta", "Descripcion": "Pimienta molida, 50g.", "Categoria": "Especias", "Precio": 1.49, "CodificacionProducto": { "Lote": "PIM123", "Vencimiento": "2023-12-31" } },
//     { "Nombre": "Chocolate", "Descripcion": "Chocolate negro, 100g.", "Categoria": "Reposteria", "Precio": 2.99, "CodificacionProducto": { "Lote": "CHOC123", "Vencimiento": "2023-11-15" } },
//     { "Nombre": "Café", "Descripcion": "Café molido, 250g.", "Categoria": "Bebidas", "Precio": 4.49, "CodificacionProducto": { "Lote": "CAFE123", "Vencimiento": "2023-11-30" } },
//     { "Nombre": "Mantequilla de Maní", "Descripcion": "Mantequilla de maní natural, 500g.", "Categoria": "Frutos Secos", "Precio": 3.99, "CodificacionProducto": { "Lote": "MM123", "Vencimiento": "2024-02-10" } },
//     { "Nombre": "Vinagre", "Descripcion": "Vinagre de vino tinto, 500ml.", "Categoria": "Condimentos", "Precio": 1.79, "CodificacionProducto": { "Lote": "VINA123", "Vencimiento": "2023-12-31" } },
//     { "Nombre": "Mostaza", "Descripcion": "Mostaza amarilla, 200g.", "Categoria": "Condimentos", "Precio": 0.99, "CodificacionProducto": { "Lote": "MOS123", "Vencimiento": "2023-12-31" } },
//     { "Nombre": "Panecillos", "Descripcion": "Panecillos de avena, paquete de 6.", "Categoria": "Panaderia", "Precio": 2.79, "CodificacionProducto": { "Lote": "PANE123", "Vencimiento": "2023-10-17" } },
//     { "Nombre": "Helado", "Descripcion": "Helado de vainilla, 1 litro.", "Categoria": "Helados", "Precio": 3.99, "CodificacionProducto": { "Lote": "HEL123", "Vencimiento": "2023-11-15" } },
//     { "Nombre": "Pepinillos", "Descripcion": "Pepinillos encurtidos, 500g.", "Categoria": "Encurtidos", "Precio": 1.69, "CodificacionProducto": { "Lote": "PEPI123", "Vencimiento": "2023-12-31" } },
//     { "Nombre": "Salsa de Tomate", "Descripcion": "Salsa de tomate, 500g.", "Categoria": "Salsas", "Precio": 1.29, "CodificacionProducto": { "Lote": "ST123", "Vencimiento": "2023-11-30" } },
//     { "Nombre": "Nueces", "Descripcion": "Nueces naturales, 250g.", "Categoria": "Frutos Secos", "Precio": 5.49, "CodificacionProducto": { "Lote": "NU123", "Vencimiento": "2024-02-28" } },
//     { "Nombre": "Jugo de Naranja", "Descripcion": "Jugo de naranja natural, 1 litro.", "Categoria": "Bebidas", "Precio": 2.49, "CodificacionProducto": { "Lote": "JN123", "Vencimiento": "2023-11-30" } },
//     { "Nombre": "Panceta", "Descripcion": "Panceta ahumada, 250g.", "Categoria": "Carnes", "Precio": 4.79, "CodificacionProducto": { "Lote": "PAN567", "Vencimiento": "2023-10-23" } },
//     { "Nombre": "Mermelada", "Descripcion": "Mermelada de fresa, 400g.", "Categoria": "Reposteria", "Precio": 2.79, "CodificacionProducto": { "Lote": "MER123", "Vencimiento": "2023-12-31" } },
//     { "Nombre": "Hamburguesas", "Descripcion": "Hamburguesas de res, paquete de 4.", "Categoria": "Carnes", "Precio": 6.29, "CodificacionProducto": { "Lote": "HAM123", "Vencimiento": "2023-10-27" } },
//     { "Nombre": "Salchichas", "Descripcion": "Salchichas de pavo, paquete de 8.", "Categoria": "Embutidos", "Precio": 3.29, "CodificacionProducto": { "Lote": "SAL123", "Vencimiento": "2023-10-30" } },
//     { "Nombre": "Aceitunas", "Descripcion": "Aceitunas verdes rellenas, 250g.", "Categoria": "Encurtidos", "Precio": 1.99, "CodificacionProducto": { "Lote": "ACEI123", "Vencimiento": "2023-12-31" } },
//     { "Nombre": "Sirope de Arce", "Descripcion": "Sirope de arce puro, 250ml.", "Categoria": "Endulzantes", "Precio": 7.99 },
//     { "Nombre": "Pasta de Dientes", "Descripcion": "Pasta de dientes fluorada, 150g.", "Categoria": "Higiene", "Precio": 2.49 },
//     { "Nombre": "Shampoo", "Descripcion": "Shampoo revitalizante, 400ml.", "Categoria": "Higiene", "Precio": 5.99 },
//     { "Nombre": "Toallas de Papel", "Descripcion": "Toallas de papel absorbentes, paquete de 6.", "Categoria": "Hogar", "Precio": 3.79 },
//     { "Nombre": "Lavavajillas", "Descripcion": "Detergente para lavavajillas, 500ml.", "Categoria": "Limpieza", "Precio": 2.99 },
//     { "Nombre": "Barras de Granola", "Descripcion": "Barras de granola, paquete de 8.", "Categoria": "Snacks", "Precio": 4.49 },
//     { "Nombre": "Té Verde", "Descripcion": "Té verde orgánico, caja de 20 bolsitas.", "Categoria": "Bebidas", "Precio": 3.29 },
//     { "Nombre": "Salmón", "Descripcion": "Filete de salmón fresco, 200g.", "Categoria": "Pescados", "Precio": 7.99, "CodificacionProducto": { "Lote": "S567", "Vencimiento": "2023-10-26" } },
//     { "Nombre": "Azúcar", "Descripcion": "Azúcar blanca, 1 kg.", "Categoria": "Endulzantes", "Precio": 1.79 },
//     { "Nombre": "Papel Higiénico", "Descripcion": "Papel higiénico suave, paquete de 12.", "Categoria": "Hogar", "Precio": 6.49 },
//     { "Nombre": "Huevos", "Descripcion": "Huevos frescos, docena.", "Categoria": "Huevos", "Precio": 2.99, "CodificacionProducto": { "Lote": "H234", "Vencimiento": "2023-10-19" } },
//     { "Nombre": "Salmón Ahumado", "Descripcion": "Salmón ahumado, 150g.", "Categoria": "Pescados", "Precio": 8.49 },
//     { "Nombre": "Queso Parmesano", "Descripcion": "Queso parmesano rallado, 100g.", "Categoria": "Lacteos", "Precio": 3.79 },
//     { "Nombre": "Mantequilla", "Descripcion": "Mantequilla sin sal, 250g.", "Categoria": "Lacteos", "Precio": 3.49 },
//     { "Nombre": "Aceitunas Rellenas", "Descripcion": "Aceitunas rellenas de pimientos, 200g.", "Categoria": "Encurtidos", "Precio": 2.19 },
//     { "Nombre": "Vino Tinto", "Descripcion": "Vino tinto reserva, 750ml.", "Categoria": "Bebidas", "Precio": 9.99 },
//     { "Nombre": "Crema de Cacahuate", "Descripcion": "Crema de cacahuate natural, 400g.", "Categoria": "Frutos Secos", "Precio": 5.29 },
//     { "Nombre": "Tortillas de Maíz", "Descripcion": "Tortillas de maíz, paquete de 12.", "Categoria": "Panes", "Precio": 1.99 },
//     { "Nombre": "Salsa de Soja", "Descripcion": "Salsa de soja tradicional, 250ml.", "Categoria": "Salsas", "Precio": 2.29 },
//     { "Nombre": "Té de Manzanilla", "Descripcion": "Té de manzanilla, caja de 25 bolsitas.", "Categoria": "Bebidas", "Precio": 2.99 },
//     { "Nombre": "Champiñones", "Descripcion": "Champiñones frescos, 200g.", "Categoria": "Verduras", "Precio": 1.79 },
//     { "Nombre": "Salmón enlatado", "Descripcion": "Salmón enlatado al natural, 150g.", "Categoria": "Pescados", "Precio": 4.99 },
//     { "Nombre": "Crema para la Piel", "Descripcion": "Crema hidratante para la piel, 200ml.", "Categoria": "Higiene", "Precio": 6.49 },
//     { "Nombre": "Gel de Ducha", "Descripcion": "Gel de ducha revitalizante, 500ml.", "Categoria": "Higiene", "Precio": 3.99 },
//     { "Nombre": "Hojuelas de Maíz", "Descripcion": "Hojuelas de maíz azucaradas, 400g.", "Categoria": "Cereales", "Precio": 2.49 },
//     { "Nombre": "Champú para Mascotas", "Descripcion": "Champú suave para mascotas, 250ml.", "Categoria": "Mascotas", "Precio": 3.29 },
//     { "Nombre": "Galletas para Perros", "Descripcion": "Galletas para perros, paquete de 200g.", "Categoria": "Mascotas", "Precio": 1.99 },
//     { "Nombre": "Comida para Gatos", "Descripcion": "Comida para gatos, lata de 400g.", "Categoria": "Mascotas", "Precio": 2.79 },
//     { "Nombre": "Papel Aluminio", "Descripcion": "Rollo de papel aluminio, 30 metros.", "Categoria": "Hogar", "Precio": 1.99 },
//     { "Nombre": "Limpiador Multiusos", "Descripcion": "Limpiador multiusos, 500ml.", "Categoria": "Limpieza", "Precio": 2.79 },
//     { "Nombre": "Detergente para Ropa", "Descripcion": "Detergente líquido para ropa, 1 litro.", "Categoria": "Limpieza", "Precio": 4.99 },
//     { "Nombre": "Pasta Dental para Niños", "Descripcion": "Pasta dental para niños, sabor fresa, 100g.", "Categoria": "Higiene", "Precio": 1.99 },
//     {"Nombre": "Pan Integral", "Descripcion": "Pan integral, 500g.", "Categoria": "Panaderia", "Precio": 2.49, "CodificacionProducto": { "Lote": "PANI123", "Vencimiento": "2023-10-20" } },
//     { "Nombre": "Peras", "Descripcion": "Peras frescas, 1 kg.", "Categoria": "Frutas", "Precio": 3.99 },
//     { "Nombre": "Uvas", "Descripcion": "Uvas frescas, 500g.", "Categoria": "Frutas", "Precio": 4.79 },
//     { "Nombre": "Pollo", "Descripcion": "Pollo fresco, 1 kg.", "Categoria": "Carnes", "Precio": 5.99 },
//     { "Nombre": "Verduras Variadas", "Descripcion": "Paquete de verduras variadas, 500g.", "Categoria": "Verduras", "Precio": 2.29 },
//     { "Nombre": "Arroz", "Descripcion": "Arroz blanco, 1 kg.", "Categoria": "Cereales", "Precio": 2.99 },
//     { "Nombre": "Aceite de Oliva", "Descripcion": "Aceite de oliva virgen extra, 500ml.", "Categoria": "Aceites", "Precio": 6.49 },
//     { "Nombre": "Vino Blanco", "Descripcion": "Vino blanco seco, 750ml.", "Categoria": "Bebidas", "Precio": 8.99 },
//     { "Nombre": "Galletas de Avena", "Descripcion": "Galletas de avena, paquete de 300g.", "Categoria": "Reposteria", "Precio": 3.29 },
//     { "Nombre": "Leche de Almendras", "Descripcion": "Leche de almendras, 1 litro.", "Categoria": "Lacteos", "Precio": 4.99 },
//     { "Nombre": "Mango", "Descripcion": "Mango fresco, 1 unidad.", "Categoria": "Frutas", "Precio": 1.49 },
//     { "Nombre": "Cereal de Maíz", "Descripcion": "Cereal de maíz, caja de 500g.", "Categoria": "Cereales", "Precio": 3.79 },
//     { "Nombre": "Yogur Griego", "Descripcion": "Yogur griego natural, 500g.", "Categoria": "Lacteos", "Precio": 2.79 },
//     { "Nombre": "Huevos", "Descripcion": "Huevos frescos, docena.", "Categoria": "Huevos", "Precio": 2.99, "CodificacionProducto": { "Lote": "H234", "Vencimiento": "2023-10-19" } },
//     { "Nombre": "Tocino", "Descripcion": "Tocino ahumado, 200g.", "Categoria": "Carnes", "Precio": 4.99 },
//     { "Nombre": "Soda", "Descripcion": "Refresco de cola, lata de 355ml.", "Categoria": "Bebidas", "Precio": 1.29 },
//     { "Nombre": "Chips de Tortilla", "Descripcion": "Chips de tortilla, bolsa de 200g.", "Categoria": "Snacks", "Precio": 2.49 },
//     { "Nombre": "Galletas de Chocolate", "Descripcion": "Galletas de chocolate, paquete de 250g.", "Categoria": "Reposteria", "Precio": 2.79 },
//     { "Nombre": "Pan Integral", "Descripcion": "Pan integral, 500g.", "Categoria": "Panaderia", "Precio": 2.49, "CodificacionProducto": { "Lote": "PANI123", "Vencimiento": "2023-10-20" } },
//     { "Nombre": "Peras", "Descripcion": "Peras frescas, 1 kg.", "Categoria": "Frutas", "Precio": 3.99 },
//     { "Nombre": "Uvas", "Descripcion": "Uvas frescas, 500g.", "Categoria": "Frutas", "Precio": 4.79 },
//     { "Nombre": "Pollo", "Descripcion": "Pollo fresco, 1 kg.", "Categoria": "Carnes", "Precio": 5.99 },
//     { "Nombre": "Verduras Variadas", "Descripcion": "Paquete de verduras variadas, 500g.", "Categoria": "Verduras", "Precio": 2.29 },
//     { "Nombre": "Arroz", "Descripcion": "Arroz blanco, 1 kg.", "Categoria": "Cereales", "Precio": 2.99 },
//     { "Nombre": "Aceite de Oliva", "Descripcion": "Aceite de oliva virgen extra, 500ml.", "Categoria": "Aceites", "Precio": 6.49 },
//     { "Nombre": "Vino Blanco", "Descripcion": "Vino blanco seco, 750ml.", "Categoria": "Bebidas", "Precio": 8.99 },
//     { "Nombre": "Galletas de Avena", "Descripcion": "Galletas de avena, paquete de 300g.", "Categoria": "Reposteria", "Precio": 3.29 },
//     { "Nombre": "Leche de Almendras", "Descripcion": "Leche de almendras, 1 litro.", "Categoria": "Lacteos", "Precio": 4.99 },
//     { "Nombre": "Mango", "Descripcion": "Mango fresco, 1 unidad.", "Categoria": "Frutas", "Precio": 1.49 },
//     { "Nombre": "Cereal de Maíz", "Descripcion": "Cereal de maíz, caja de 500g.", "Categoria": "Cereales", "Precio": 3.79 },
//     { "Nombre": "Yogur Griego", "Descripcion": "Yogur griego natural, 500g.", "Categoria": "Lacteos", "Precio": 2.79 },
//     { "Nombre": "Huevos", "Descripcion": "Huevos frescos, docena.", "Categoria": "Huevos", "Precio": 2.99, "CodificacionProducto": { "Lote": "H234", "Vencimiento": "2023-10-19" } },
//     { "Nombre": "Tocino", "Descripcion": "Tocino ahumado, 200g.", "Categoria": "Carnes", "Precio": 4.99 },
//     { "Nombre": "Soda", "Descripcion": "Refresco de cola, lata de 355ml.", "Categoria": "Bebidas", "Precio": 1.29 },
//     { "Nombre": "Chips de Tortilla", "Descripcion": "Chips de tortilla, bolsa de 200g.", "Categoria": "Snacks", "Precio": 2.49 },
//     { "Nombre": "Galletas de Chocolate", "Descripcion": "Galletas de chocolate, paquete de 250g.", "Categoria": "Reposteria", "Precio": 2.79 },
//     { "Nombre": "Pan Integral", "Descripcion": "Pan integral, 500g.", "Categoria": "Panaderia", "Precio": 2.49, "CodificacionProducto": { "Lote": "PANI123", "Vencimiento": "2023-10-20" } },
//     { "Nombre": "Peras", "Descripcion": "Peras frescas, 1 kg.", "Categoria": "Frutas", "Precio": 3.99 },
//     { "Nombre": "Uvas", "Descripcion": "Uvas frescas, 500g.", "Categoria": "Frutas", "Precio": 4.79 },
//     { "Nombre": "Pollo", "Descripcion": "Pollo fresco, 1 kg.", "Categoria": "Carnes", "Precio": 5.99 },
//     { "Nombre": "Verduras Variadas", "Descripcion": "Paquete de verduras variadas, 500g.", "Categoria": "Verduras", "Precio": 2.29 },
//     { "Nombre": "Arroz", "Descripcion": "Arroz blanco, 1 kg.", "Categoria": "Cereales", "Precio": 2.99 },
//     { "Nombre": "Aceite de Oliva", "Descripcion": "Aceite de oliva virgen extra, 500ml.", "Categoria": "Aceites", "Precio": 6.49 },
//     { "Nombre": "Vino Blanco", "Descripcion": "Vino blanco seco, 750ml.", "Categoria": "Bebidas", "Precio": 8.99 },
//     { "Nombre": "Galletas de Avena", "Descripcion": "Galletas de avena, paquete de 300g.", "Categoria": "Reposteria", "Precio": 3.29 },
//     { "Nombre": "Leche de Almendras", "Descripcion": "Leche de almendras, 1 litro.", "Categoria": "Lacteos", "Precio": 4.99 },
//     { "Nombre": "Mango", "Descripcion": "Mango fresco, 1 unidad.", "Categoria": "Frutas", "Precio": 1.49 },
//     { "Nombre": "Cereal de Maíz", "Descripcion": "Cereal de maíz, caja de 500g.", "Categoria": "Cereales", "Precio": 3.79 },
//     { "Nombre": "Yogur Griego", "Descripcion": "Yogur griego natural, 500g.", "Categoria": "Lacteos", "Precio": 2.79 },
//     { "Nombre": "Huevos", "Descripcion": "Huevos frescos, docena.", "Categoria": "Huevos", "Precio": 2.99, "CodificacionProducto": { "Lote": "H234", "Vencimiento": "2023-10-19" } },
//     { "Nombre": "Tocino", "Descripcion": "Tocino ahumado, 200g.", "Categoria": "Carnes", "Precio": 4.99 },
//     { "Nombre": "Soda", "Descripcion": "Refresco de cola, lata de 355ml.", "Categoria": "Bebidas", "Precio": 1.29 },
//     { "Nombre": "Chips de Tortilla", "Descripcion": "Chips de tortilla, bolsa de 200g.", "Categoria": "Snacks", "Precio": 2.49 },
//     { "Nombre": "Galletas de Chocolate", "Descripcion": "Galletas de chocolate, paquete de 250g.", "Categoria": "Reposteria", "Precio": 2.79 },
//     { "Nombre": "Pan Integral", "Descripcion": "Pan integral, 500g.", "Categoria": "Panaderia", "Precio": 2.49, "CodificacionProducto": { "Lote": "PANI123", "Vencimiento": "2023-10-20" } },
//     { "Nombre": "Peras", "Descripcion": "Peras frescas, 1 kg.", "Categoria": "Frutas", "Precio": 3.99 },
//     { "Nombre": "Uvas", "Descripcion": "Uvas frescas, 500g.", "Categoria": "Frutas", "Precio": 4.79 },
//     { "Nombre": "Pollo", "Descripcion": "Pollo fresco, 1 kg.", "Categoria": "Carnes", "Precio": 5.99 },
//     { "Nombre": "Verduras Variadas", "Descripcion": "Paquete de verduras variadas, 500g.", "Categoria": "Verduras", "Precio": 2.29 },
//     { "Nombre": "Arroz", "Descripcion": "Arroz blanco, 1 kg.", "Categoria": "Cereales", "Precio": 2.99 },
//     { "Nombre": "Aceite de Oliva", "Descripcion": "Aceite de oliva virgen extra, 500ml.", "Categoria": "Aceites", "Precio": 6.49 },
//     { "Nombre": "Vino Blanco", "Descripcion": "Vino blanco seco, 750ml.", "Categoria": "Bebidas", "Precio": 8.99 },
//     { "Nombre": "Galletas de Avena", "Descripcion": "Galletas de avena, paquete de 300g.", "Categoria": "Reposteria", "Precio": 3.29 },
//     { "Nombre": "Leche de Almendras", "Descripcion": "Leche de almendras, 1 litro.", "Categoria": "Lacteos", "Precio": 4.99 },
//     { "Nombre": "Mango", "Descripcion": "Mango fresco, 1 unidad.", "Categoria": "Frutas", "Precio": 1.49 },
//     { "Nombre": "Cereal de Maíz", "Descripcion": "Cereal de maíz, caja de 500g.", "Categoria": "Cereales", "Precio": 3.79 },
//     { "Nombre": "Yogur Griego", "Descripcion": "Yogur griego natural, 500g.", "Categoria": "Lacteos", "Precio": 2.79 },
//     { "Nombre": "Huevos", "Descripcion": "Huevos frescos, docena.", "Categoria": "Huevos", "Precio": 2.99, "CodificacionProducto": { "Lote": "H234", "Vencimiento": "2023-10-19" } },
//     { "Nombre": "Tocino", "Descripcion": "Tocino ahumado, 200g.", "Categoria": "Carnes", "Precio": 4.99 },
//     { "Nombre": "Soda", "Descripcion": "Refresco de cola, lata de 355ml.", "Categoria": "Bebidas", "Precio": 1.29 },
//     { "Nombre": "Chips de Tortilla", "Descripcion": "Chips de tortilla, bolsa de 200g.", "Categoria": "Snacks", "Precio": 2.49 },
//     { "Nombre": "Galletas de Chocolate", "Descripcion": "Galletas de chocolate, paquete de 250g.", "Categoria": "Reposteria", "Precio": 2.79 },
//     {"Nombre": "Cerveza", "Descripcion": "Cerveza rubia, lata de 500ml.", "Categoria": "Bebidas", "Precio": 1.99 },
//     { "Nombre": "Pasta", "Descripcion": "Pasta de trigo, paquete de 500g.", "Categoria": "Cereales", "Precio": 1.49, "CodificacionProducto": { "Lote": "PASTA123", "Vencimiento": "2024-01-15" } },
//     { "Nombre": "Fresas", "Descripcion": "Fresas frescas, 250g.", "Categoria": "Frutas", "Precio": 2.99 },
//     { "Nombre": "Salmón", "Descripcion": "Filete de salmón fresco, 200g.", "Categoria": "Pescados", "Precio": 7.99, "CodificacionProducto": { "Lote": "S567", "Vencimiento": "2023-10-26" } },
//     { "Nombre": "Miel", "Descripcion": "Miel de abeja natural, 500g.", "Categoria": "Endulzantes", "Precio": 4.29 },
//     { "Nombre": "Pan de Centeno", "Descripcion": "Pan de centeno, 400g.", "Categoria": "Panaderia", "Precio": 2.99, "CodificacionProducto": { "Lote": "PANC123", "Vencimiento": "2023-10-22" } },
//     { "Nombre": "Manzanas", "Descripcion": "Manzanas frescas, 1 kg.", "Categoria": "Frutas", "Precio": 2.79 },
//     { "Nombre": "Té Negro", "Descripcion": "Té negro inglés, caja de 20 bolsitas.", "Categoria": "Bebidas", "Precio": 2.49 },
//     { "Nombre": "Yogur de Vainilla", "Descripcion": "Yogur de vainilla, 150g.", "Categoria": "Lacteos", "Precio": 1.29 },
//     { "Nombre": "Pimienta", "Descripcion": "Pimienta molida, 50g.", "Categoria": "Especias", "Precio": 1.49, "CodificacionProducto": { "Lote": "PIM123", "Vencimiento": "2023-12-31" } },
//     { "Nombre": "Papel Higiénico", "Descripcion": "Papel higiénico suave, paquete de 12.", "Categoria": "Hogar", "Precio": 6.49 },
//     { "Nombre": "Aceitunas Rellenas", "Descripcion": "Aceitunas rellenas de pimientos, 200g.", "Categoria": "Encurtidos", "Precio": 2.19 },
//     { "Nombre": "Azúcar", "Descripcion": "Azúcar blanca, 1 kg.", "Categoria": "Endulzantes", "Precio": 1.79 },
//     { "Nombre": "Jabón de Manos", "Descripcion": "Jabón líquido para manos, 250ml.", "Categoria": "Higiene", "Precio": 1.99 },
//     { "Nombre": "Limpiador Multiusos", "Descripcion": "Limpiador multiusos, 500ml.", "Categoria": "Limpieza", "Precio": 2.79 },
//     { "Nombre": "Pasta Dental", "Descripcion": "Pasta dental blanqueadora, 150g.", "Categoria": "Higiene", "Precio": 2.19 },
//     { "Nombre": "Queso Cheddar", "Descripcion": "Queso cheddar rallado, 200g.", "Categoria": "Lacteos", "Precio": 2.99 },
//     { "Nombre": "Café Molido", "Descripcion": "Café molido, 250g.", "Categoria": "Bebidas", "Precio": 3.49 },
//     { "Nombre": "Crema de Cacahuate", "Descripcion": "Crema de cacahuate natural, 400g.", "Categoria": "Frutos Secos", "Precio": 5.29 },
//     { "Nombre": "Pepinillos", "Descripcion": "Pepinillos encurtidos, 500g.", "Categoria": "Encurtidos", "Precio": 1.69 },
//     { "Nombre": "Pasta de Tomate", "Descripcion": "Pasta de tomate, lata de 400g.", "Categoria": "Salsas", "Precio": 1.29 },
//     { "Nombre": "Té de Manzanilla", "Descripcion": "Té de manzanilla, caja de 25 bolsitas.", "Categoria": "Bebidas", "Precio": 2.99 },
//     { "Nombre": "Hamburguesas de Pavo", "Descripcion": "Hamburguesas de pavo, paquete de 4.", "Categoria": "Carnes", "Precio": 5.49 },
//     { "Nombre": "Champiñones", "Descripcion": "Champiñones frescos, 200g.", "Categoria": "Verduras", "Precio": 1.79 },
//     { "Nombre": "Arándanos", "Descripcion": "Arándanos frescos, 150g.", "Categoria": "Frutas", "Precio": 3.99 },
//     { "Nombre": "Galletas de Avena", "Descripcion": "Galletas de avena, paquete de 300g.", "Categoria": "Reposteria", "Precio": 3.29 },
//     { "Nombre": "Lechuga", "Descripcion": "Lechuga fresca, 1 unidad.", "Categoria": "Verduras", "Precio": 1.49 },
//     { "Nombre": "Mantequilla", "Descripcion": "Mantequilla sin sal, 250g.", "Categoria": "Lacteos", "Precio": 3.49 },
//     { "Nombre": "Nueces", "Descripcion": "Nueces naturales, 250g.", "Categoria": "Frutos Secos", "Precio": 5.49, "CodificacionProducto": { "Lote": "NU123", "Vencimiento": "2024-02-28" } },
//     { "Nombre": "Jugo de Naranja", "Descripcion": "Jugo de naranja natural, 1 litro.", "Categoria": "Bebidas", "Precio": 2.49, "CodificacionProducto": { "Lote": "JN123", "Vencimiento": "2023-11-30" } },
//     { "Nombre": "Panecillos", "Descripcion": "Panecillos de avena, paquete de 6.", "Categoria": "Panaderia", "Precio": 2.79 },
//     { "Nombre": "Huevos", "Descripcion": "Huevos frescos, docena.", "Categoria": "Huevos", "Precio": 2.99, "CodificacionProducto": { "Lote": "H234", "Vencimiento": "2023-10-19" } },
//     { "Nombre": "Acelgas", "Descripcion": "Acelgas frescas, 300g.", "Categoria": "Verduras", "Precio": 1.99 },
//     { "Nombre": "Salmón Ahumado", "Descripcion": "Salmón ahumado, 150g.", "Categoria": "Pescados", "Precio": 8.49 },
//     { "Nombre": "Chips de Plátano", "Descripcion": "Chips de plátano, bolsa de 150g.", "Categoria": "Snacks", "Precio": 2.99 },
//     { "Nombre": "Pimientos Rojos", "Descripcion": "Pimientos rojos frescos, 200g.", "Categoria": "Verduras", "Precio": 2.49 },
//     { "Nombre": "Hummus", "Descripcion": "Hummus de garbanzo, 200g.", "Categoria": "Aperitivos", "Precio": 2.29 },
//     { "Nombre": "Pasta de Dientes", "Descripcion": "Pasta de dientes, 150g.", "Categoria": "Higiene", "Precio": 1.79 },
//     { "Nombre": "Tortillas de Maíz", "Descripcion": "Tortillas de maíz, paquete de 12.", "Categoria": "Panes", "Precio": 1.99 },
//     { "Nombre": "Salsa de Soja", "Descripcion": "Salsa de soja tradicional, 250ml.", "Categoria": "Salsas", "Precio": 2.29 },
//     { "Nombre": "Pañuelos de Papel", "Descripcion": "Pañuelos de papel, paquete de 80.", "Categoria": "Hogar", "Precio": 1.29 },
//     { "Nombre": "Té de Hibisco", "Descripcion": "Té de hibisco, caja de 20 bolsitas.", "Categoria": "Bebidas", "Precio": 3.99 },
//     { "Nombre": "Champú Suave", "Descripcion": "Champú suave, 400ml.", "Categoria": "Higiene", "Precio": 3.49 },
//     { "Nombre": "Panecillos de Centeno", "Descripcion": "Panecillos de centeno, paquete de 6.", "Categoria": "Panaderia", "Precio": 3.29 },
//     { "Nombre": "Cacahuetes", "Descripcion": "Cacahuetes tostados y salados, 200g.", "Categoria": "Frutos Secos", "Precio": 2.99 },
//     { "Nombre": "Puré de Tomate", "Descripcion": "Puré de tomate, lata de 400g.", "Categoria": "Salsas", "Precio": 1.49 },
//     { "Nombre": "Vino Tinto", "Descripcion": "Vino tinto reserva, 750ml.", "Categoria": "Bebidas", "Precio": 9.99 },
//     { "Nombre": "Cerveza Artesanal", "Descripcion": "Cerveza artesanal, botella de 330ml.", "Categoria": "Bebidas", "Precio": 3.49 },
//     { "Nombre": "Camarones", "Descripcion": "Camarones frescos, 300g.", "Categoria": "Mariscos", "Precio": 9.99, "CodificacionProducto": { "Lote": "CAM567", "Vencimiento": "2023-10-28" } },
//     { "Nombre": "Mermelada de Fresa", "Descripcion": "Mermelada de fresa, frasco de 350g.", "Categoria": "Reposteria", "Precio": 2.79 },
//     { "Nombre": "Cerveza IPA", "Descripcion": "Cerveza IPA, botella de 500ml.", "Categoria": "Bebidas", "Precio": 4.99 },
//     { "Nombre": "Tofu", "Descripcion": "Tofu fresco, 400g.", "Categoria": "Vegetarianos", "Precio": 2.29 },
//     { "Nombre": "Barras de Granola", "Descripcion": "Barras de granola, paquete de 8.", "Categoria": "Snacks", "Precio": 4.49 },
//     { "Nombre": "Té Verde", "Descripcion": "Té verde orgánico, caja de 20 bolsitas.", "Categoria": "Bebidas", "Precio": 3.29 },
//     { "Nombre": "Salmón", "Descripcion": "Filete de salmón fresco, 200g.", "Categoria": "Pescados", "Precio": 7.99, "CodificacionProducto": { "Lote": "S567", "Vencimiento": "2023-10-26" } },
//     { "Nombre": "Azúcar", "Descripcion": "Azúcar blanca, 1 kg.", "Categoria": "Endulzantes", "Precio": 1.79 },
//     { "Nombre": "Papel Higiénico", "Descripcion": "Papel higiénico suave, paquete de 12.", "Categoria": "Hogar", "Precio": 6.49 },
//     { "Nombre": "Huevos", "Descripcion": "Huevos frescos, docena.", "Categoria": "Huevos", "Precio": 2.99, "CodificacionProducto": { "Lote": "H234", "Vencimiento": "2023-10-19" } },
//     { "Nombre": "Salmón Ahumado", "Descripcion": "Salmón ahumado, 150g.", "Categoria": "Pescados", "Precio": 8.49 },
//     { "Nombre": "Queso Parmesano", "Descripcion": "Queso parmesano rallado, 100g.", "Categoria": "Lacteos", "Precio": 3.79 },
//     { "Nombre": "Mantequilla", "Descripcion": "Mantequilla sin sal, 250g.", "Categoria": "Lacteos", "Precio": 3.49 },
//     { "Nombre": "Aceitunas Rellenas", "Descripcion": "Aceitunas rellenas de pimientos, 200g.", "Categoria": "Encurtidos", "Precio": 2.19 },
//     { "Nombre": "Vino Tinto", "Descripcion": "Vino tinto reserva, 750ml.", "Categoria": "Bebidas", "Precio": 9.99 },
//     { "Nombre": "Cerveza IPA", "Descripcion": "Cerveza IPA, botella de 500ml.", "Categoria": "Bebidas", "Precio": 4.99 },
//     { "Nombre": "Tofu", "Descripcion": "Tofu fresco, 400g.", "Categoria": "Vegetarianos", "Precio": 2.29 },
//     { "Nombre": "Barras de Granola", "Descripcion": "Barras de granola, paquete de 8.", "Categoria": "Snacks", "Precio": 4.49 },
//     { "Nombre": "Té Verde", "Descripcion": "Té verde orgánico, caja de 20 bolsitas.", "Categoria": "Bebidas", "Precio": 3.29 },
//     {"Nombre": "Aceite de Coco", "Descripcion": "Aceite de coco virgen extra.", "Categoria": "Aceites", "Precio": 6.99, "CodificacionProducto": { "Lote": "U234", "Vencimiento": "2024-05-10" } },
//     { "Nombre": "Panceta", "Descripcion": "Panceta ahumada, 250g.", "Categoria": "Carnes", "Precio": 4.79, "CodificacionProducto": { "Lote": "PAN567", "Vencimiento": "2023-10-23" } },
//     { "Nombre": "Cerveza", "Descripcion": "Cerveza rubia, lata de 500ml.", "Categoria": "Bebidas", "Precio": 1.99 },
//     { "Nombre": "Pasta", "Descripcion": "Pasta de trigo, paquete de 500g.", "Categoria": "Cereales", "Precio": 1.49, "CodificacionProducto": { "Lote": "PASTA123", "Vencimiento": "2024-01-15" } },
//     { "Nombre": "Fresas", "Descripcion": "Fresas frescas, 250g.", "Categoria": "Frutas", "Precio": 2.99 },
//     { "Nombre": "Salmón", "Descripcion": "Filete de salmón fresco, 200g.", "Categoria": "Pescados", "Precio": 7.99, "CodificacionProducto": { "Lote": "S567", "Vencimiento": "2023-10-26" } },
//     { "Nombre": "Miel", "Descripcion": "Miel de abeja natural, 500g.", "Categoria": "Endulzantes", "Precio": 4.29 },
//     { "Nombre": "Pan de Centeno", "Descripcion": "Pan de centeno, 400g.", "Categoria": "Panaderia", "Precio": 2.99, "CodificacionProducto": { "Lote": "PANC123", "Vencimiento": "2023-10-22" } },
//     { "Nombre": "Manzanas", "Descripcion": "Manzanas frescas, 1 kg.", "Categoria": "Frutas", "Precio": 2.79 },
//     { "Nombre": "Té Negro", "Descripcion": "Té negro inglés, caja de 20 bolsitas.", "Categoria": "Bebidas", "Precio": 2.49 },
//     { "Nombre": "Yogur de Vainilla", "Descripcion": "Yogur de vainilla, 150g.", "Categoria": "Lacteos", "Precio": 1.29 },
//     { "Nombre": "Pimienta", "Descripcion": "Pimienta molida, 50g.", "Categoria": "Especias", "Precio": 1.49, "CodificacionProducto": { "Lote": "PIM123", "Vencimiento": "2023-12-31" } },
//     { "Nombre": "Papel Higiénico", "Descripcion": "Papel higiénico suave, paquete de 12.", "Categoria": "Hogar", "Precio": 6.49 },
//     { "Nombre": "Aceitunas Rellenas", "Descripcion": "Aceitunas rellenas de pimientos, 200g.", "Categoria": "Encurtidos", "Precio": 2.19 },
//     { "Nombre": "Azúcar", "Descripcion": "Azúcar blanca, 1 kg.", "Categoria": "Endulzantes", "Precio": 1.79 },
//     { "Nombre": "Jabón de Manos", "Descripcion": "Jabón líquido para manos, 250ml.", "Categoria": "Higiene", "Precio": 1.99 },
//     { "Nombre": "Limpiador Multiusos", "Descripcion": "Limpiador multiusos, 500ml.", "Categoria": "Limpieza", "Precio": 2.79 },
//     { "Nombre": "Pasta Dental", "Descripcion": "Pasta dental blanqueadora, 150g.", "Categoria": "Higiene", "Precio": 2.19 },
//     { "Nombre": "Queso Cheddar", "Descripcion": "Queso cheddar rallado, 200g.", "Categoria": "Lacteos", "Precio": 2.99 },
//     { "Nombre": "Café Molido", "Descripcion": "Café molido, 250g.", "Categoria": "Bebidas", "Precio": 3.49 },
//     { "Nombre": "Crema de Cacahuate", "Descripcion": "Crema de cacahuate natural, 400g.", "Categoria": "Frutos Secos", "Precio": 5.29 },
//     { "Nombre": "Pepinillos", "Descripcion": "Pepinillos encurtidos, 500g.", "Categoria": "Encurtidos", "Precio": 1.69 },
//     { "Nombre": "Pasta de Tomate", "Descripcion": "Pasta de tomate, lata de 400g.", "Categoria": "Salsas", "Precio": 1.29 },
//     { "Nombre": "Té de Manzanilla", "Descripcion": "Té de manzanilla, caja de 25 bolsitas.", "Categoria": "Bebidas", "Precio": 2.99 },
//     { "Nombre": "Hamburguesas de Pavo", "Descripcion": "Hamburguesas de pavo, paquete de 4.", "Categoria": "Carnes", "Precio": 5.49 },
//     { "Nombre": "Champiñones", "Descripcion": "Champiñones frescos, 200g.", "Categoria": "Verduras", "Precio": 1.79 },
//     { "Nombre": "Arándanos", "Descripcion": "Arándanos frescos, 150g.", "Categoria": "Frutas", "Precio": 3.99 },
//     { "Nombre": "Galletas de Avena", "Descripcion": "Galletas de avena, paquete de 300g.", "Categoria": "Reposteria", "Precio": 3.29 },
//     { "Nombre": "Lechuga", "Descripcion": "Lechuga fresca, 1 unidad.", "Categoria": "Verduras", "Precio": 1.49 },
//     { "Nombre": "Mantequilla", "Descripcion": "Mantequilla sin sal, 250g.", "Categoria": "Lacteos", "Precio": 3.49 },
//     { "Nombre": "Nueces", "Descripcion": "Nueces naturales, 250g.", "Categoria": "Frutos Secos", "Precio": 5.49, "CodificacionProducto": { "Lote": "NU123", "Vencimiento": "2024-02-28" } },
//     { "Nombre": "Jugo de Naranja", "Descripcion": "Jugo de naranja natural, 1 litro.", "Categoria": "Bebidas", "Precio": 2.49, "CodificacionProducto": { "Lote": "JN123", "Vencimiento": "2023-11-30" } },
//     { "Nombre": "Panecillos", "Descripcion": "Panecillos de avena, paquete de 6.", "Categoria": "Panaderia", "Precio": 2.79 },
//     { "Nombre": "Huevos", "Descripcion": "Huevos frescos, docena.", "Categoria": "Huevos", "Precio": 2.99, "CodificacionProducto": { "Lote": "H234", "Vencimiento": "2023-10-19" } },
//     { "Nombre": "Acelgas", "Descripcion": "Acelgas frescas, 300g.", "Categoria": "Verduras", "Precio": 1.99 },
//     { "Nombre": "Salmón Ahumado", "Descripcion": "Salmón ahumado, 150g.", "Categoria": "Pescados", "Precio": 8.49 },
//     { "Nombre": "Chips de Plátano", "Descripcion": "Chips de plátano, bolsa de 150g.", "Categoria": "Snacks", "Precio": 2.99 },
//     { "Nombre": "Pimientos Rojos", "Descripcion": "Pimientos rojos frescos, 200g.", "Categoria": "Verduras", "Precio": 2.49 },
//     { "Nombre": "Hummus", "Descripcion": "Hummus de garbanzo, 200g.", "Categoria": "Aperitivos", "Precio": 2.29 },
//     { "Nombre": "Pasta de Dientes", "Descripcion": "Pasta de dientes, 150g.", "Categoria": "Higiene", "Precio": 1.79 },
//     { "Nombre": "Tortillas de Maíz", "Descripcion": "Tortillas de maíz, paquete de 12.", "Categoria": "Panes", "Precio": 1.99 },
//     { "Nombre": "Salsa de Soja", "Descripcion": "Salsa de soja tradicional, 250ml.", "Categoria": "Salsas", "Precio": 2.29 },
//     { "Nombre": "Pañuelos de Papel", "Descripcion": "Pañuelos de papel, paquete de 80.", "Categoria": "Hogar", "Precio": 1.29 },
//     { "Nombre": "Té de Hibisco", "Descripcion": "Té de hibisco, caja de 20 bolsitas.", "Categoria": "Bebidas", "Precio": 3.99 },
//     { "Nombre": "Champú Suave", "Descripcion": "Champú suave, 400ml.", "Categoria": "Higiene", "Precio": 3.49 },
//     { "Nombre": "Panecillos de Centeno", "Descripcion": "Panecillos de centeno, paquete de 6.", "Categoria": "Panaderia", "Precio": 3.29 },
//     { "Nombre": "Cacahuetes", "Descripcion": "Cacahuetes tostados y salados, 200g.", "Categoria": "Frutos Secos", "Precio": 2.99 },
//     { "Nombre": "Puré de Tomate", "Descripcion": "Puré de tomate, lata de 400g.", "Categoria": "Salsas", "Precio": 1.49 },
//     { "Nombre": "Vino Tinto", "Descripcion": "Vino tinto reserva, 750ml.", "Categoria": "Bebidas", "Precio": 9.99 },
//     { "Nombre": "Cerveza IPA", "Descripcion": "Cerveza IPA, botella de 500ml.", "Categoria": "Bebidas", "Precio": 4.99 },
//     { "Nombre": "Tofu", "Descripcion": "Tofu fresco, 400g.", "Categoria": "Vegetarianos", "Precio": 2.29 },
//     { "Nombre": "Barras de Granola", "Descripcion": "Barras de granola, paquete de 8.", "Categoria": "Snacks", "Precio": 4.49 },
//     { "Nombre": "Té Verde", "Descripcion": "Té verde orgánico, caja de 20 bolsitas.", "Categoria": "Bebidas", "Precio": 3.29 },
//     { "Nombre": "Salmón", "Descripcion": "Filete de salmón fresco, 200g.", "Categoria": "Pescados", "Precio": 7.99, "CodificacionProducto": { "Lote": "S567", "Vencimiento": "2023-10-26" } },
//     { "Nombre": "Azúcar", "Descripcion": "Azúcar blanca, 1 kg.", "Categoria": "Endulzantes", "Precio": 1.79 },
//     { "Nombre": "Papel Higiénico", "Descripcion": "Papel higiénico suave, paquete de 12.", "Categoria": "Hogar", "Precio": 6.49 },
//     { "Nombre": "Huevos", "Descripcion": "Huevos frescos, docena.", "Categoria": "Huevos", "Precio": 2.99, "CodificacionProducto": { "Lote": "H234", "Vencimiento": "2023-10-19" } },
//     { "Nombre": "Salmón Ahumado", "Descripcion": "Salmón ahumado, 150g.", "Categoria": "Pescados", "Precio": 8.49 },
//     { "Nombre": "Queso Parmesano", "Descripcion": "Queso parmesano rallado, 100g.", "Categoria": "Lacteos", "Precio": 3.79 },
//     { "Nombre": "Mantequilla", "Descripcion": "Mantequilla sin sal, 250g.", "Categoria": "Lacteos", "Precio": 3.49 },
//     { "Nombre": "Aceitunas Rellenas", "Descripcion": "Aceitunas rellenas de pimientos, 200g.", "Categoria": "Encurtidos", "Precio": 2.19 },
//     { "Nombre": "Vino Tinto", "Descripcion": "Vino tinto reserva, 750ml.", "Categoria": "Bebidas", "Precio": 9.99 },
//     { "Nombre": "Cerveza IPA", "Descripcion": "Cerveza IPA, botella de 500ml.", "Categoria": "Bebidas", "Precio": 4.99 },
//     { "Nombre": "Tofu", "Descripcion": "Tofu fresco, 400g.", "Categoria": "Vegetarianos", "Precio": 2.29 },
//     { "Nombre": "Barras de Granola", "Descripcion": "Barras de granola, paquete de 8.", "Categoria": "Snacks", "Precio": 4.49 },
//     { "Nombre": "Té Verde", "Descripcion": "Té verde orgánico, caja de 20 bolsitas.", "Categoria": "Bebidas", "Precio": 3.29 },
//     {"Nombre": "Té de Manzanilla", "Descripcion": "Té de manzanilla, caja de 25 bolsitas.", "Categoria": "Bebidas", "Precio": 2.99 },
//     { "Nombre": "Hamburguesas de Pavo", "Descripcion": "Hamburguesas de pavo, paquete de 4.", "Categoria": "Carnes", "Precio": 5.49 },
//     { "Nombre": "Champiñones", "Descripcion": "Champiñones frescos, 200g.", "Categoria": "Verduras", "Precio": 1.79 },
//     { "Nombre": "Arándanos", "Descripcion": "Arándanos frescos, 150g.", "Categoria": "Frutas", "Precio": 3.99 },
//     { "Nombre": "Galletas de Avena", "Descripcion": "Galletas de avena, paquete de 300g.", "Categoria": "Reposteria", "Precio": 3.29 },
//     { "Nombre": "Lechuga", "Descripcion": "Lechuga fresca, 1 unidad.", "Categoria": "Verduras", "Precio": 1.49 },
//     { "Nombre": "Mantequilla", "Descripcion": "Mantequilla sin sal, 250g.", "Categoria": "Lacteos", "Precio": 3.49 },
//     { "Nombre": "Nueces", "Descripcion": "Nueces naturales, 250g.", "Categoria": "Frutos Secos", "Precio": 5.49, "CodificacionProducto": { "Lote": "NU123", "Vencimiento": "2024-02-28" } },
//     { "Nombre": "Jugo de Naranja", "Descripcion": "Jugo de naranja natural, 1 litro.", "Categoria": "Bebidas", "Precio": 2.49, "CodificacionProducto": { "Lote": "JN123", "Vencimiento": "2023-11-30" } },
//     { "Nombre": "Panecillos", "Descripcion": "Panecillos de avena, paquete de 6.", "Categoria": "Panaderia", "Precio": 2.79 },
//     { "Nombre": "Huevos", "Descripcion": "Huevos frescos, docena.", "Categoria": "Huevos", "Precio": 2.99, "CodificacionProducto": { "Lote": "H234", "Vencimiento": "2023-10-19" } },
//     { "Nombre": "Acelgas", "Descripcion": "Acelgas frescas, 300g.", "Categoria": "Verduras", "Precio": 1.99 },
//     { "Nombre": "Salmón Ahumado", "Descripcion": "Salmón ahumado, 150g.", "Categoria": "Pescados", "Precio": 8.49 },
//     { "Nombre": "Chips de Plátano", "Descripcion": "Chips de plátano, bolsa de 150g.", "Categoria": "Snacks", "Precio": 2.99 },
//     { "Nombre": "Pimientos Rojos", "Descripcion": "Pimientos rojos frescos, 200g.", "Categoria": "Verduras", "Precio": 2.49 },
//     {"Nombre": "Cerveza", "Descripcion": "Cerveza rubia, lata de 500ml.", "Categoria": "Bebidas", "Precio": 1.99 },
//     { "Nombre": "Pasta", "Descripcion": "Pasta de trigo, paquete de 500g.", "Categoria": "Cereales", "Precio": 1.49, "CodificacionProducto": { "Lote": "PASTA123", "Vencimiento": "2024-01-15" } },
//     { "Nombre": "Fresas", "Descripcion": "Fresas frescas, 250g.", "Categoria": "Frutas", "Precio": 2.99 },
//     { "Nombre": "Salmón", "Descripcion": "Filete de salmón fresco, 200g.", "Categoria": "Pescados", "Precio": 7.99, "CodificacionProducto": { "Lote": "S567", "Vencimiento": "2023-10-26" } },
//     { "Nombre": "Miel", "Descripcion": "Miel de abeja natural, 500g.", "Categoria": "Endulzantes", "Precio": 4.29 },
//     { "Nombre": "Pan de Centeno", "Descripcion": "Pan de centeno, 400g.", "Categoria": "Panaderia", "Precio": 2.99, "CodificacionProducto": { "Lote": "PANC123", "Vencimiento": "2023-10-22" } },
//     { "Nombre": "Manzanas", "Descripcion": "Manzanas frescas, 1 kg.", "Categoria": "Frutas", "Precio": 2.79 },
//     { "Nombre": "Té Negro", "Descripcion": "Té negro inglés, caja de 20 bolsitas.", "Categoria": "Bebidas", "Precio": 2.49 },
//     { "Nombre": "Yogur de Vainilla", "Descripcion": "Yogur de vainilla, 150g.", "Categoria": "Lacteos", "Precio": 1.29 },
//     { "Nombre": "Pimienta", "Descripcion": "Pimienta molida, 50g.", "Categoria": "Especias", "Precio": 1.49, "CodificacionProducto": { "Lote": "PIM123", "Vencimiento": "2023-12-31" } },
//     { "Nombre": "Papel Higiénico", "Descripcion": "Papel higiénico suave, paquete de 12.", "Categoria": "Hogar", "Precio": 6.49 },
//     { "Nombre": "Aceitunas Rellenas", "Descripcion": "Aceitunas rellenas de pimientos, 200g.", "Categoria": "Encurtidos", "Precio": 2.19 },
//     { "Nombre": "Azúcar", "Descripcion": "Azúcar blanca, 1 kg.", "Categoria": "Endulzantes", "Precio": 1.79 },
//     { "Nombre": "Jabón de Manos", "Descripcion": "Jabón líquido para manos, 250ml.", "Categoria": "Higiene", "Precio": 1.99 },
//     { "Nombre": "Limpiador Multiusos", "Descripcion": "Limpiador multiusos, 500ml.", "Categoria": "Limpieza", "Precio": 2.79 },
//     { "Nombre": "Pasta Dental", "Descripcion": "Pasta dental blanqueadora, 150g.", "Categoria": "Higiene", "Precio": 2.19 },
//     { "Nombre": "Queso Cheddar", "Descripcion": "Queso cheddar rallado, 200g.", "Categoria": "Lacteos", "Precio": 2.99 },
//     { "Nombre": "Café Molido", "Descripcion": "Café molido, 250g.", "Categoria": "Bebidas", "Precio": 3.49 },
//     { "Nombre": "Crema de Cacahuate", "Descripcion": "Crema de cacahuate natural, 400g.", "Categoria": "Frutos Secos", "Precio": 5.29 },
//     { "Nombre": "Pepinillos", "Descripcion": "Pepinillos encurtidos, 500g.", "Categoria": "Encurtidos", "Precio": 1.69 },
//     { "Nombre": "Pasta de Tomate", "Descripcion": "Pasta de tomate, lata de 400g.", "Categoria": "Salsas", "Precio": 1.29 },
//     { "Nombre": "Té de Manzanilla", "Descripcion": "Té de manzanilla, caja de 25 bolsitas.", "Categoria": "Bebidas", "Precio": 2.99 },
//     { "Nombre": "Hamburguesas de Pavo", "Descripcion": "Hamburguesas de pavo, paquete de 4.", "Categoria": "Carnes", "Precio": 5.49 },
//     { "Nombre": "Champiñones", "Descripcion": "Champiñones frescos, 200g.", "Categoria": "Verduras", "Precio": 1.79 },
//     { "Nombre": "Arándanos", "Descripcion": "Arándanos frescos, 150g.", "Categoria": "Frutas", "Precio": 3.99 },
//     { "Nombre": "Galletas de Avena", "Descripcion": "Galletas de avena, paquete de 300g.", "Categoria": "Reposteria", "Precio": 3.29 },
//     { "Nombre": "Lechuga", "Descripcion": "Lechuga fresca, 1 unidad.", "Categoria": "Verduras", "Precio": 1.49 },
//     { "Nombre": "Mantequilla", "Descripcion": "Mantequilla sin sal, 250g.", "Categoria": "Lacteos", "Precio": 3.49 },
//     { "Nombre": "Nueces", "Descripcion": "Nueces naturales, 250g.", "Categoria": "Frutos Secos", "Precio": 5.49, "CodificacionProducto": { "Lote": "NU123", "Vencimiento": "2024-02-28" } },
//     { "Nombre": "Jugo de Naranja", "Descripcion": "Jugo de naranja natural, 1 litro.", "Categoria": "Bebidas", "Precio": 2.49, "CodificacionProducto": { "Lote": "JN123", "Vencimiento": "2023-11-30" } },
//     { "Nombre": "Panecillos", "Descripcion": "Panecillos de avena, paquete de 6.", "Categoria": "Panaderia", "Precio": 2.79 },
//     { "Nombre": "Huevos", "Descripcion": "Huevos frescos, docena.", "Categoria": "Huevos", "Precio": 2.99, "CodificacionProducto": { "Lote": "H234", "Vencimiento": "2023-10-19" } },
//     { "Nombre": "Acelgas", "Descripcion": "Acelgas frescas, 300g.", "Categoria": "Verduras", "Precio": 1.99 },
//     { "Nombre": "Salmón Ahumado", "Descripcion": "Salmón ahumado, 150g.", "Categoria": "Pescados", "Precio": 8.49 },
//     { "Nombre": "Chips de Plátano", "Descripcion": "Chips de plátano, bolsa de 150g.", "Categoria": "Snacks", "Precio": 2.99 },
//     { "Nombre": "Pimientos Rojos", "Descripcion": "Pimientos rojos frescos, 200g.", "Categoria": "Verduras", "Precio": 2.49 },
//     { "Nombre": "Hummus", "Descripcion": "Hummus de garbanzo, 200g.", "Categoria": "Aperitivos", "Precio": 2.29 },
//     { "Nombre": "Pasta de Dientes", "Descripcion": "Pasta de dientes, 150g.", "Categoria": "Higiene", "Precio": 1.79 },
//     { "Nombre": "Tortillas de Maíz", "Descripcion": "Tortillas de maíz, paquete de 12.", "Categoria": "Panes", "Precio": 1.99 },
//     { "Nombre": "Salsa de Soja", "Descripcion": "Salsa de soja tradicional, 250ml.", "Categoria": "Salsas", "Precio": 2.29 },
//     { "Nombre": "Pañuelos de Papel", "Descripcion": "Pañuelos de papel, paquete de 80.", "Categoria": "Hogar", "Precio": 1.29 },
//     { "Nombre": "Té de Hibisco", "Descripcion": "Té de hibisco, caja de 20 bolsitas.", "Categoria": "Bebidas", "Precio": 3.99 },
//     { "Nombre": "Champú Suave", "Descripcion": "Champú suave, 400ml.", "Categoria": "Higiene", "Precio": 3.49 },
//     { "Nombre": "Panecillos de Centeno", "Descripcion": "Panecillos de centeno, paquete de 6.", "Categoria": "Panaderia", "Precio": 3.29 },
//     { "Nombre": "Cacahuetes", "Descripcion": "Cacahuetes tostados y salados, 200g.", "Categoria": "Frutos Secos", "Precio": 2.99 },
//     { "Nombre": "Puré de Tomate", "Descripcion": "Puré de tomate, lata de 400g.", "Categoria": "Salsas", "Precio": 1.49 },
//     { "Nombre": "Vino Tinto", "Descripcion": "Vino tinto reserva, 750ml.", "Categoria": "Bebidas", "Precio": 9.99 },
//     { "Nombre": "Cerveza IPA", "Descripcion": "Cerveza IPA, botella de 500ml.", "Categoria": "Bebidas", "Precio": 4.99 },
//     { "Nombre": "Tofu", "Descripcion": "Tofu fresco, 400g.", "Categoria": "Vegetarianos", "Precio": 2.29 },
//     { "Nombre": "Barras de Granola", "Descripcion": "Barras de granola, paquete de 8.", "Categoria": "Snacks", "Precio": 4.49 },
//     { "Nombre": "Té Verde", "Descripcion": "Té verde orgánico, caja de 20 bolsitas.", "Categoria": "Bebidas", "Precio": 3.29 },
//     { "Nombre": "Salmón", "Descripcion": "Filete de salmón fresco, 200g.", "Categoria": "Pescados", "Precio": 7.99, "CodificacionProducto": { "Lote": "S567", "Vencimiento": "2023-10-26" } },
//     { "Nombre": "Azúcar", "Descripcion": "Azúcar blanca, 1 kg.", "Categoria": "Endulzantes", "Precio": 1.79 },
//     { "Nombre": "Papel Higiénico", "Descripcion": "Papel higiénico suave, paquete de 12.", "Categoria": "Hogar", "Precio": 6.49 },
//     { "Nombre": "Huevos", "Descripcion": "Huevos frescos, docena.", "Categoria": "Huevos", "Precio": 2.99, "CodificacionProducto": { "Lote": "H234", "Vencimiento": "2023-10-19" } },
//     { "Nombre": "Salmón Ahumado", "Descripcion": "Salmón ahumado, 150g.", "Categoria": "Pescados", "Precio": 8.49 },
//     { "Nombre": "Queso Parmesano", "Descripcion": "Queso parmesano rallado, 100g.", "Categoria": "Lacteos", "Precio": 3.79 },
//     { "Nombre": "Mantequilla", "Descripcion": "Mantequilla sin sal, 250g.", "Categoria": "Lacteos", "Precio": 3.49 },
//     { "Nombre": "Aceitunas Rellenas", "Descripcion": "Aceitunas rellenas de pimientos, 200g.", "Categoria": "Encurtidos", "Precio": 2.19 },
//     { "Nombre": "Vino Tinto", "Descripcion": "Vino tinto reserva, 750ml.", "Categoria": "Bebidas", "Precio": 9.99 },
//     {"Nombre": "Té Verde", "Descripcion": "Té verde orgánico, caja de 20 bolsitas.", "Categoria": "Bebidas", "Precio": 3.29 },
//     { "Nombre": "Cerveza IPA", "Descripcion": "Cerveza IPA, botella de 500ml.", "Categoria": "Bebidas", "Precio": 4.99 },
//     { "Nombre": "Tofu", "Descripcion": "Tofu fresco, 400g.", "Categoria": "Vegetarianos", "Precio": 2.29 },
//     { "Nombre": "Barras de Granola", "Descripcion": "Barras de granola, paquete de 8.", "Categoria": "Snacks", "Precio": 4.49 },
//     { "Nombre": "Té Verde", "Descripcion": "Té verde orgánico, caja de 20 bolsitas.", "Categoria": "Bebidas", "Precio": 3.29 }
// ]);

// db.getCollection('Productos').find();

//db.getCollection('Productos').findOne();

//db.getCollection('Productos').updateOne({Nombre: 'Leche'},{$set:{Precio:3.99}});

//db.getCollection('Productos').updateMany({Categoria: 'Lácteos'},{$set:{Precio:3.99}});